aspire_web/blueprints/tutors/views.py
from flask import Blueprint, flash, render_template,request,redirect,url_for,session,abort
from models.tutor import Tutor
import boto3, botocore
from config import Config
from api.util.helpers import upload_file_to_s3
from werkzeug.utils import secure_filename

S3_KEY=Config.S3_KEY
S3_SECRET=Config.S3_SECRET
S3_BUCKET=Config.S3_BUCKET
S3_LOCATION=Config.S3_LOCATION


tutors_blueprint = Blueprint('tutors',
                            __name__,
                            template_folder='templates')

# @tutors_blueprint.route('/create')
# def create():

#     new_tutor = Tutor(
#         first_name="Jane",
#         last_name= "Doe",
#         age=34,
#         is_female= True,
#         email= 'ABC4@gmail.com',
#         password='ABC4@gmail.com',
#     )

#     if new_tutor.save():
#         flash("Tutor created!")

#         # updating username
#         username = new_tutor.first_name+new_tutor.last_name+str(new_tutor.id)
#         new_tutor.username=username
#         new_tutor.save()

#         return redirect(url_for('home'))
#     else:
#         flash("Unable to create Tutor!")
#         return render_template('home.html', errors = new_tutor.errors)

@tutors_blueprint.route('/profile-photo')
def upload_profile():
    return render_template('tutors/profile_photo.html')

@tutors_blueprint.route('/profile-photo', methods=['POST'])
def upload():
    tutor = Tutor.get_by_id(1) #hard coded for testing purposes

    file = request.files["profile_photo"]
    file.filename = secure_filename(file.filename)
    image_path = upload_file_to_s3(file, "tutor", tutor.username)

    # save photo url in database
    tutor.profile_image=image_path

    if tutor.save(only=[Tutor.profile_image]):
        flash("Profile photo saved to database successfully!",'info')
    else:
        flash("Unable to save profile photo to database.",'danger')
    return render_template('home.html',errors=tutor.errors)

aspire_web/blueprints/tutors/templates/tutors/new.html
{% extends "_layout.html" %}

{% block title %}
Create a tutor account
{% endblock %}

{% block header %}
{% endblock %}

{% block content %}

<h1>Create a tutor account</h1>
<form action="{{url_for('tutors.create')}}" method="POST">
    <label for="email">Email</label>
    <input type="email" name="email" id="email">
    <label for="password">Password</label>
    <input type="password" name="password" id="password">
    <label for="first_name">First name</label>
    <input type="text" name="first_name" id="first_name">
    <label for="last_name">Last name</label>
    <input type="text" name="last_name" id="last_name">
    <label for="age" id="age" name="age">Age</label>
    <input type="number" name="age" id="age" min="1" max="130">
    <br />
    Gender
    <br />
    <input type="radio" id="male" name="male" value="male">
    <label for="male">Male</label><br>
    <input type="radio" id="female" name="female" value="female">
    <label for="female">Female</label><br>
    <input type="submit" class="btn btn-primary" value="Submit">
</form>

{% endblock %}

aspire_web/blueprints/tutors/templates/tutors/profile_photo.html
{% extends "_layout.html" %}

{% block title %}
Upload Profile Photo
{% endblock %}

{% block header %}
{% endblock %}

{% block content %}
<form action="{{url_for('tutors.upload')}}" method="POST" enctype="multipart/form-data">
  <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
  <input type="file" name="profile_photo">
  <input type="submit" value="Submit">
</form>


<img src="{{image}}" alt="{{image}}" width="50%">

{% endblock %}